version: 1
frontend:
    phases:
        preBuild:
            commands:
                - npm ci --cache .npm --prefer-offline
        build:
            commands:
                - env | grep -e DATABASE_URL -e NEXTAUTH_SECRET -e GITHUB_ID -e GITHUB_SECRET -e GOOGLE_CLIENT_ID -e GOOGLE_CLIENT_SECRET -e NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME >> .env.production
                - npx prisma generate && next build
    artifacts:
        baseDirectory: .next
        files:
            - "**/*"
    cache:
        paths:
            - node_modules/**/*
